### ISSUE TITLE
Make icon for audio/video files more obvious

### ISSUE THREAD

**Issue by jeremyboggs** [scholarslab/cville_rally_theme#13]
- Update the icon, with some verbage indicating there's a movie to watch;
- See if we can generate a screen grab from the video itself;
- Consider displaying the icon in a way different from image thumbnails;

**Comment by jeremyboggs** [comment]
Let's also investigate whether we can filter the default thumbnails using the theme's `custom.php` file. If not, we may need to write a separate plugin to do this.

**Comment by eam5** [comment]
added new fallback images to /images

Fixed in 1872e45e7ab63c80553a170e994d1cbb9e5c1f38
