### ISSUE TITLE
Update form field labels and descriptions

### ISSUE THREAD

**Issue by jeremyboggs** [scholarslab/cville_rally_theme#2]
Update form labels and descriptions as follows:

---

*REQUIRED: Title*
For example, “Police in downtown Charlottesville,” “Difficult conversations,” or “What I witnessed from the Rotunda.”
 
*Tell your story*
Include as much detail as you wish—we want to hear your experiences!

*Upload a file*
File too big to upload? You can make it smaller or contact us at digital_collecting@virginia.edu, we’ll be happy to help.

*Description*
Please include as much information as you can. For example: What was happening at this moment? Who is involved? What else do we need to know about this moment in time?

*Date*
When did this occur?
 
*Location*
Where did this occur?

*Your name (optional)*
 
*REQUIRED: Your email*

*Sharing checkbox* - You may share my contribution publicly. Uncheck to share only with approved researchers.

*Anonymous checkbox* - Do not display my name publicly. Note: If you provide your name, we are able to hide it from any resulting public exhibitions. However, we are not able to guarantee full anonymity. If you are concerned about your identity being known, we recommend not providing your name in the form above.

**Comment by amber-reichert** [comment]
@jeremyboggs: This is outdated, I will create new Issues for remaining edits (which are relatively few).
