### ISSUE TITLE
Find better way to convey T+C: pop-up that user has to acknowledge? 

### ISSUE THREAD

**Issue by amber-reichert** [scholarslab/cville_rally_theme#8]
Linking to T+C on a secondary page isn't an ideal way to convey them. Consider pop-up or inline T+C for next iteration.

**Comment by jeremyboggs** [comment]
@amber-reichert Could we discuss this a bit more? Maybe sketch out some options before deciding on one to try to implement?

**Comment by jeremyboggs** [comment]
@amber-reichert In 3782ecd3e7e8f18fa2e1cc4a618889e97481d169, @eam5 updated the contribution form to present a link to the T&C before encountering the form. Also, she added a summary of the T&C to a side column. I think this might be enough to address your concerns, but we can discuss more.

**Comment by amber-reichert** [comment]
Nice! Sounds like a good solution to me...
